name: Main Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        cache-disabled: true

    - name: Build with Gradle
      run: ./gradlew build

    - name: Conditionally set SKIP_TESTS for main repo
      if: github.repository == 'Monika-Protivova-Backend-Development/kotlin-essentials'
      run: echo "SKIP_TESTS=true" >> $GITHUB_ENV

    - name: Run all tests
      if: ${{ github.ref != 'refs/heads/main' || env.SKIP_TESTS != 'true' }}
      run: ./gradlew test
